import "dotenv/config";
import { spawnSync } from "node:child_process";
import { renameSync, writeFileSync } from "node:fs";
import process from "node:process";
import { Client } from "pg";

const outputPath = "src/types/database.types.ts";

type ColumnRow = {
  table_name: string;
  table_type: "BASE TABLE" | "VIEW";
  column_name: string;
  is_nullable: "YES" | "NO";
  data_type: string;
  udt_name: string;
  column_default: string | null;
  is_identity: "YES" | "NO";
  is_generated: "ALWAYS" | "NEVER";
};

type EnumRow = {
  enum_name: string;
  enum_value: string;
};

type ForeignKeyRow = {
  constraint_name: string;
  table_name: string;
  column_name: string;
  foreign_table_name: string;
  foreign_column_name: string;
  is_one_to_one: boolean;
};

type RoutineParameterRow = {
  specific_name: string;
  routine_name: string;
  return_data_type: string;
  return_udt_name: string;
  parameter_name: string | null;
  parameter_mode: "IN" | "OUT" | "INOUT" | null;
  data_type: string | null;
  udt_name: string | null;
  ordinal_position: number | null;
};

type RoutineDefinition = {
  name: string;
  returnDataType: string;
  returnUdtName: string;
  parameters: RoutineParameterRow[];
};

function requiredEnv(name: string) {
  const value = process.env[name]?.trim();
  if (!value) throw new Error(`Missing required environment variable: ${name}`);
  return value;
}

function writeTypes(contents: string) {
  const temporaryPath = `${outputPath}.tmp`;
  writeFileSync(temporaryPath, contents, "utf8");
  renameSync(temporaryPath, outputPath);
}

function tryOfficialGenerator() {
  const accessToken = process.env.SUPABASE_ACCESS_TOKEN?.trim();
  const projectId = process.env.SUPABASE_PROJECT_ID?.trim();
  if (!accessToken || !projectId) return false;

  const result = spawnSync(
    "supabase",
    [
      "gen",
      "types",
      "typescript",
      "--project-id",
      projectId,
      "--schema",
      "public",
    ],
    { encoding: "utf8", env: process.env },
  );

  if (result.status !== 0 || !result.stdout.trim()) {
    const safeError = `${result.stderr}\n${result.stdout}`
      .replaceAll(accessToken, "[access-token-redacted]")
      .trim();
    throw new Error(safeError || "Official Supabase type generation failed");
  }

  writeTypes(
    `// Generated by the official Supabase CLI. Do not edit manually.\n${result.stdout}`,
  );
  console.log(`Generated ${outputPath} with the official Supabase CLI`);
  return true;
}

function propertyName(value: string) {
  return JSON.stringify(value);
}

function scalarType(udtName: string, enumNames: Set<string>) {
  if (enumNames.has(udtName)) {
    return `Database["public"]["Enums"][${propertyName(udtName)}]`;
  }

  if (
    [
      "int2",
      "int4",
      "int8",
      "float4",
      "float8",
      "numeric",
      "money",
    ].includes(udtName)
  ) {
    return "number";
  }
  if (udtName === "bool") return "boolean";
  if (udtName === "json" || udtName === "jsonb") return "Json";
  return "string";
}

function columnType(column: ColumnRow, enumNames: Set<string>) {
  if (column.data_type === "ARRAY" || column.udt_name.startsWith("_")) {
    return `${scalarType(column.udt_name.replace(/^_/, ""), enumNames)}[]`;
  }
  return scalarType(column.udt_name, enumNames);
}

function routineValueType(
  dataType: string | null,
  udtName: string | null,
  enumNames: Set<string>,
) {
  if (!udtName) return "unknown";
  if (dataType === "ARRAY" || udtName.startsWith("_")) {
    return `${scalarType(udtName.replace(/^_/, ""), enumNames)}[]`;
  }
  return scalarType(udtName, enumNames);
}

function renderShape(
  columns: ColumnRow[],
  enumNames: Set<string>,
  mode: "Row" | "Insert" | "Update",
) {
  const lines = ["{"];
  for (const column of columns) {
    const generated =
      column.is_generated === "ALWAYS" || column.is_identity === "YES";
    const optional =
      mode === "Update" ||
      generated ||
      column.is_nullable === "YES" ||
      column.column_default !== null;
    const suffix = mode === "Row" ? "" : optional ? "?" : "";
    const baseType =
      generated && mode !== "Row"
        ? "never"
        : columnType(column, enumNames);
    const nullable =
      column.is_nullable === "YES" && !(generated && mode !== "Row")
        ? " | null"
        : "";
    lines.push(
      `  ${propertyName(column.column_name)}${suffix}: ${baseType}${nullable}`,
    );
  }
  lines.push("}");
  return lines;
}

function indent(lines: string[], depth: number) {
  const prefix = "  ".repeat(depth);
  return lines.map((line) => `${prefix}${line}`);
}

async function generateFromCatalog() {
  const parsedUrl = new URL(requiredEnv("SUPABASE_DB_URL"));
  const client = new Client({
    host: parsedUrl.hostname,
    port: parsedUrl.port ? Number(parsedUrl.port) : 5432,
    user: decodeURIComponent(parsedUrl.username),
    password: decodeURIComponent(parsedUrl.password),
    database: parsedUrl.pathname.replace(/^\//, "") || "postgres",
    ssl:
      parsedUrl.searchParams.get("sslmode") === "disable"
        ? undefined
        : { rejectUnauthorized: false },
  });

  await client.connect();
  try {
    // A pg Client executes one query at a time. Keep these sequential so type
    // generation remains compatible with pg@9 instead of relying on its old
    // implicit query queue.
    const columnResult = await client.query<ColumnRow>(`
        select c.table_name, t.table_type, c.column_name, c.is_nullable,
          c.data_type, c.udt_name, c.column_default, c.is_identity,
          c.is_generated
        from information_schema.columns c
        join information_schema.tables t
          on t.table_schema = c.table_schema and t.table_name = c.table_name
        where c.table_schema = 'public'
          and t.table_type in ('BASE TABLE', 'VIEW')
        order by c.table_name, c.ordinal_position
      `);
    const enumResult = await client.query<EnumRow>(`
        select typ.typname as enum_name, en.enumlabel as enum_value
        from pg_type typ
        join pg_enum en on en.enumtypid = typ.oid
        join pg_namespace ns on ns.oid = typ.typnamespace
        where ns.nspname = 'public'
        order by typ.typname, en.enumsortorder
      `);
    const foreignKeyResult = await client.query<ForeignKeyRow>(`
        select tc.constraint_name, tc.table_name, kcu.column_name,
          ccu.table_name as foreign_table_name,
          ccu.column_name as foreign_column_name,
          exists (
            select 1
            from pg_constraint uc
            join pg_class cls on cls.oid = uc.conrelid
            join pg_namespace ns on ns.oid = cls.relnamespace
            join pg_attribute attr
              on attr.attrelid = cls.oid and attr.attnum = any(uc.conkey)
            where ns.nspname = 'public'
              and cls.relname = tc.table_name
              and uc.contype in ('p', 'u')
              and cardinality(uc.conkey) = 1
              and attr.attname = kcu.column_name
          ) as is_one_to_one
        from information_schema.table_constraints tc
        join information_schema.key_column_usage kcu
          on kcu.constraint_schema = tc.constraint_schema
          and kcu.constraint_name = tc.constraint_name
        join information_schema.constraint_column_usage ccu
          on ccu.constraint_schema = tc.constraint_schema
          and ccu.constraint_name = tc.constraint_name
        where tc.constraint_schema = 'public'
          and tc.constraint_type = 'FOREIGN KEY'
        order by tc.table_name, tc.constraint_name, kcu.ordinal_position
      `);
    const routineResult = await client.query<RoutineParameterRow>(`
        select r.specific_name, r.routine_name,
          r.data_type as return_data_type,
          r.type_udt_name as return_udt_name,
          p.parameter_name, p.parameter_mode, p.data_type, p.udt_name,
          p.ordinal_position
        from information_schema.routines r
        left join information_schema.parameters p
          on p.specific_schema = r.specific_schema
          and p.specific_name = r.specific_name
        where r.specific_schema = 'public'
          and r.routine_type = 'FUNCTION'
          and r.data_type <> 'trigger'
        order by r.routine_name, r.specific_name, p.ordinal_position
      `);

    const enums = new Map<string, string[]>();
    for (const row of enumResult.rows) {
      const values = enums.get(row.enum_name) ?? [];
      values.push(row.enum_value);
      enums.set(row.enum_name, values);
    }
    const enumNames = new Set(enums.keys());

    const tables = new Map<string, ColumnRow[]>();
    const views = new Map<string, ColumnRow[]>();
    for (const column of columnResult.rows) {
      const target = column.table_type === "VIEW" ? views : tables;
      const columns = target.get(column.table_name) ?? [];
      columns.push(column);
      target.set(column.table_name, columns);
    }

    const relationships = new Map<string, ForeignKeyRow[]>();
    for (const relationship of foreignKeyResult.rows) {
      const rows = relationships.get(relationship.table_name) ?? [];
      rows.push(relationship);
      relationships.set(relationship.table_name, rows);
    }

    const routinesBySpecificName = new Map<string, RoutineDefinition>();
    for (const row of routineResult.rows) {
      const routine = routinesBySpecificName.get(row.specific_name) ?? {
        name: row.routine_name,
        returnDataType: row.return_data_type,
        returnUdtName: row.return_udt_name,
        parameters: [],
      };
      if (row.parameter_name) routine.parameters.push(row);
      routinesBySpecificName.set(row.specific_name, routine);
    }

    const routines = new Map<string, RoutineDefinition>();
    for (const routine of routinesBySpecificName.values()) {
      if (routines.has(routine.name)) {
        throw new Error(
          `Catalog fallback cannot safely render overloaded function ${routine.name}; use the official Supabase CLI generator`,
        );
      }
      routines.set(routine.name, routine);
    }

    const output = [
      "// Generated from the linked Supabase Postgres schema. Do not edit manually.",
      "export type Json =",
      "  | string",
      "  | number",
      "  | boolean",
      "  | null",
      "  | { [key: string]: Json | undefined }",
      "  | Json[]",
      "",
      "export type Database = {",
      "  public: {",
      "    Tables: {",
    ];

    for (const [tableName, columns] of tables) {
      output.push(`      ${propertyName(tableName)}: {`);
      for (const mode of ["Row", "Insert", "Update"] as const) {
        output.push(`        ${mode}:`);
        output.push(...indent(renderShape(columns, enumNames, mode), 4));
      }
      output.push("        Relationships: [");
      for (const relation of relationships.get(tableName) ?? []) {
        output.push("          {");
        output.push(
          `            foreignKeyName: ${propertyName(relation.constraint_name)}`,
          `            columns: [${propertyName(relation.column_name)}]`,
          `            isOneToOne: ${relation.is_one_to_one}`,
          `            referencedRelation: ${propertyName(relation.foreign_table_name)}`,
          `            referencedColumns: [${propertyName(relation.foreign_column_name)}]`,
        );
        output.push("          },");
      }
      output.push("        ]", "      }");
    }

    output.push("    }");
    if (views.size === 0) {
      output.push("    Views: { [_ in never]: never }");
    } else {
      output.push("    Views: {");
      for (const [viewName, columns] of views) {
        output.push(`      ${propertyName(viewName)}: {`, "        Row:");
        output.push(...indent(renderShape(columns, enumNames, "Row"), 4));
        output.push("        Relationships: []", "      }");
      }
      output.push("    }");
    }
    if (routines.size === 0) {
      output.push("    Functions: { [_ in never]: never }");
    } else {
      output.push("    Functions: {");
      for (const routine of routines.values()) {
        const inputs = routine.parameters.filter(
          (parameter) =>
            parameter.parameter_mode === "IN" ||
            parameter.parameter_mode === "INOUT",
        );
        const outputs = routine.parameters.filter(
          (parameter) =>
            parameter.parameter_mode === "OUT" ||
            parameter.parameter_mode === "INOUT",
        );

        output.push(`      ${propertyName(routine.name)}: {`, "        Args: {");
        for (const parameter of inputs) {
          output.push(
            `          ${propertyName(parameter.parameter_name!)}: ${routineValueType(parameter.data_type, parameter.udt_name, enumNames)}`,
          );
        }
        output.push("        }");

        if (outputs.length > 0) {
          output.push("        Returns: {");
          for (const parameter of outputs) {
            output.push(
              `          ${propertyName(parameter.parameter_name!)}: ${routineValueType(parameter.data_type, parameter.udt_name, enumNames)}`,
            );
          }
          output.push("        }[]");
        } else if (routine.returnDataType === "void") {
          output.push("        Returns: undefined");
        } else {
          output.push(
            `        Returns: ${routineValueType(routine.returnDataType, routine.returnUdtName, enumNames)}`,
          );
        }
        output.push("      }");
      }
      output.push("    }");
    }
    output.push("    Enums: {");
    for (const [enumName, values] of enums) {
      output.push(
        `      ${propertyName(enumName)}: ${values.map(propertyName).join(" | ")}`,
      );
    }
    output.push(
      "    }",
      "    CompositeTypes: { [_ in never]: never }",
      "  }",
      "}",
      "",
    );

    writeTypes(output.join("\n"));
    console.log(
      `Generated ${outputPath} from PostgreSQL catalog (${tables.size} tables, ${routines.size} functions, ${enums.size} enums)`,
    );
  } finally {
    await client.end();
  }
}

async function main() {
  if (!tryOfficialGenerator()) {
    await generateFromCatalog();
  }
}

void main();
